#!/bin/bash
#BSUB -J adig_ips
#BSUB -o %J.out
#BSUB -e %J.err
#BSUB -q parallel
#BSUB -P crf
#BSUB -n 16
#

module load java/1.8.0_60

export _JAVA_OPTIONS=''

cd /scratch/projects/crf/pdam-genome/data/ref
sed 's/\*//g' AcroporaDigitifera.pep > AcroporaDigitifera_clean.pep
interproscan.sh -i AcroporaDigitifera_clean.pep -b adig_ips --goterms

sed -n 's/\(aug_v2a.........\).*\(GO:.*\)/\1 \2/p' adig_ips.tsv | sort | uniq | awk -F' ' -v OFS=', ' '{x=$1;$1="";a[x]=a[x]$0}END{for(x in a)print x,a[x]}' | sed 's/, , /\t/g' > adig_ips_GO.txt
