#!/bin/bash
#BSUB -J ofav_ips
#BSUB -o %J.out
#BSUB -e %J.err
#BSUB -q parallel
#BSUB -P crf
#BSUB -n 16
#

module load java/1.8.0_60

export _JAVA_OPTIONS=''

cd /scratch/projects/crf/pdam-genome/data/ref
sed 's/\*//g' OrbicellaFaveolata.pep > OrbicellaFaveolata_clean.pep
interproscan.sh -i OrbicellaFaveolata_clean.pep -b ofav_ips --goterms

sed -n 's/\(ofav.*-RA\).*\(GO:.*\)/\1 \2/p' ofav_ips.tsv | sort | uniq | awk -F' ' -v OFS=', ' '{x=$1;$1="";a[x]=a[x]$0}END{for(x in a)print x,a[x]}' | sed 's/, , /\t/g' > ofav_ips_GO.txt
