#!/bin/bash
#BSUB -J spis_ips
#BSUB -o %J.out
#BSUB -e %J.err
#BSUB -q parallel
#BSUB -P crf
#BSUB -n 16
#

module load java/1.8.0_60

export _JAVA_OPTIONS=''

cd /scratch/projects/crf/pdam-genome/data/ref
sed 's/\*//g' StylophoraPistillata.pep > StylophoraPistillata_clean.pep
interproscan.sh -i StylophoraPistillata_clean.pep -b spis_ips --goterms

sed -n 's/\(Spis[0-9]*\).*\(GO:.*\)/\1 \2/p' spis_ips.tsv | sort | uniq | awk -F' ' -v OFS=', ' '{x=$1;$1="";a[x]=a[x]$0}END{for(x in a)print x,a[x]}' | sed 's/, , /\t/g' > spis_ips_GO.txt
