# output/Makefile

# Get Supplementary Table S1
### generated in supplement.Rmd

# Get Supplementary Table S2
### generated in supplement.Rmd

# Get Supplementary Data S1
### generated in supplement.Rmd

# Get Supplementary Data S2
cp ../orthologs/coral_specific/coral_specific_signal_transduction_genes.fasta Supplementary_Data_S2.fasta

# Get Supplementary Data S3
cp ../orthologs/species_diversified/species_specific_expansions_tophits.txt Supplementary_Data_S3.txt

# Get Table 1

# Get Table 2

# Get Table 3
### generated in supplement.Rmd

# Get Figure 1

# Get Figure 2

# Get Figure 3

# Get Figure 4